name = "ukraine-will-stand"
type = "javascript"
account_id = "864cdf76f8254fb5539425299984d766"
usage_model = "unbound"
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-02-25"

kv_namespaces = [
  {binding = "KV", id = "184700d0b0d4457a9490c2de864e5190", preview_id = "184700d0b0d4457a9490c2de864e5190"}
]

[build]
command = "yarn build"

[build.upload]
format = "modules"
main = "./dist/worker.mjs"
